# This is a basic workflow to help you get started with Actions
name: Basic GitHub OIDC Integration

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_timestamp_to_S3:

    runs-on: ubuntu-latest
    env:
       AWS_DEFAULT_REGION: 'us-west-2'
       AWS_ACCOUNT_NUMBER: ${{ secrets.AWS_ACCOUNT_NUMBER }}
       AWS_IAM_ROLE_NAME: ${{ secrets.AWS_IAM_ROLE_NAME }}
       AWS_PUSH_BUCKET: ${{ secrets.AWS_PUSH_BUCKET }}
    steps:
    
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_NUMBER}}:role/${{env.AWS_IAM_ROLE_NAME}}
          aws-region: ${{env.AWS_DEFAULT_REGION}}

      - name: Dump latest timestamp
        run: |
          timestamp=$(date +'%Y-%m-%d %H:%M:%S')
          echo "$timestamp" > /tmp/last_build.txt
          
      - name: Push timestamp to AWS
        run: |
          aws s3 cp /tmp/last_build.txt s3://${AWS_PUSH_BUCKET}
